# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-25 09:50
from __future__ import unicode_literals

import charactersheet.models.choices
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralCharacterInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('alignment', models.CharField(choices=[(charactersheet.models.choices.AlignmentChoices('Lawful Good'), 'Lawful Good'), (charactersheet.models.choices.AlignmentChoices('Neutral Good'), 'Neutral Good'), (charactersheet.models.choices.AlignmentChoices('Chaotic Good'), 'Chaotic Good'), (charactersheet.models.choices.AlignmentChoices('Lawful Neutral'), 'Lawful Neutral'), (charactersheet.models.choices.AlignmentChoices('True Neutral'), 'True Neutral'), (charactersheet.models.choices.AlignmentChoices('Chaotic Neutral'), 'Chaotic Neutral'), (charactersheet.models.choices.AlignmentChoices('Lawful Evil'), 'Lawful Evil'), (charactersheet.models.choices.AlignmentChoices('Neutral Evil'), 'Neutral Evil'), (charactersheet.models.choices.AlignmentChoices('Chaotic Evil'), 'Chaotic Evil')], max_length=30, verbose_name='Alignment')),
                ('eye_color', models.CharField(max_length=20, verbose_name='Eye color')),
                ('hair_color', models.CharField(max_length=25, null=True, verbose_name='Hair color')),
                ('homeland', models.CharField(max_length=50, null=True, verbose_name='Homeland')),
                ('deity', models.CharField(max_length=40, null=True, verbose_name='Deity')),
                ('height', models.PositiveSmallIntegerField(verbose_name='Height in centimeters')),
                ('weight', models.PositiveSmallIntegerField(verbose_name='Weight in kilograms')),
                ('gender', models.CharField(max_length=20, verbose_name='Gender')),
                ('race', models.CharField(choices=[(charactersheet.models.choices.RaceChoices('Elf'), 'Elf'), (charactersheet.models.choices.RaceChoices('Dwarf'), 'Dwarf'), (charactersheet.models.choices.RaceChoices('Gnome'), 'Gnome'), (charactersheet.models.choices.RaceChoices('Human'), 'Human'), (charactersheet.models.choices.RaceChoices('Half-elf'), 'Half-elf'), (charactersheet.models.choices.RaceChoices('Half-orc'), 'Half-orc'), (charactersheet.models.choices.RaceChoices('Halfling'), 'Halfling')], max_length=20, verbose_name='Race')),
                ('level', models.PositiveSmallIntegerField(verbose_name='Character level')),
            ],
        ),
    ]
