# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-25 11:31
from __future__ import unicode_literals

import charactersheet.models.choices
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charactersheet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterBaseStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength', models.PositiveSmallIntegerField(verbose_name='Strength')),
                ('dexterity', models.PositiveSmallIntegerField(verbose_name='Dexterity')),
                ('constituation', models.PositiveSmallIntegerField(verbose_name='Constitution')),
                ('intelligence', models.PositiveSmallIntegerField(verbose_name='Intelligence')),
                ('wisdom', models.PositiveSmallIntegerField(verbose_name='Wisdom')),
                ('charisma', models.PositiveSmallIntegerField(verbose_name='Charisma')),
            ],
        ),
        migrations.AddField(
            model_name='generalcharacterinfo',
            name='classes',
            field=models.CharField(choices=[(charactersheet.models.choices.ClassChoices('Bard'), 'Bard'), (charactersheet.models.choices.ClassChoices('Barbarian'), 'Barbarian'), (charactersheet.models.choices.ClassChoices('Cleric'), 'Cleric'), (charactersheet.models.choices.ClassChoices('Druid'), 'Druid'), (charactersheet.models.choices.ClassChoices('Fighter'), 'Fighter'), (charactersheet.models.choices.ClassChoices('Monk'), 'Monk'), (charactersheet.models.choices.ClassChoices('Paladin'), 'Paladin'), (charactersheet.models.choices.ClassChoices('Ranger'), 'Ranger'), (charactersheet.models.choices.ClassChoices('Rogue'), 'Rogue'), (charactersheet.models.choices.ClassChoices('Sorcerer'), 'Sorcerer'), (charactersheet.models.choices.ClassChoices('Wizard'), 'Wizard')], max_length=40, null=True, verbose_name='Classes'),
        ),
        migrations.AddField(
            model_name='generalcharacterinfo',
            name='player',
            field=models.CharField(max_length=50, null=True, verbose_name='Player name'),
        ),
        migrations.AddField(
            model_name='generalcharacterinfo',
            name='size',
            field=models.CharField(choices=[(charactersheet.models.choices.SizeChoices('Tiny'), 'Tiny'), (charactersheet.models.choices.SizeChoices('Small'), 'Small'), (charactersheet.models.choices.SizeChoices('Medium'), 'Medium'), (charactersheet.models.choices.SizeChoices('Large'), 'Large'), (charactersheet.models.choices.SizeChoices('Huge'), 'Huge')], max_length=10, null=True, verbose_name='Size'),
        ),
        migrations.AlterField(
            model_name='generalcharacterinfo',
            name='gender',
            field=models.CharField(choices=[(charactersheet.models.choices.GenderChoices('Male'), 'Male'), (charactersheet.models.choices.GenderChoices('Femala'), 'Femala')], max_length=20, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='characterbasestatistics',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charactersheet.GeneralCharacterInfo'),
        ),
    ]
